### ISSUE TITLE
Auth config is not used in the client

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/django-activiti#1]
Steps to reproduce:
1. Go to the admin page of `ActivitiConfig`
2. Fill in the form including username and password and click "opslaan"
3. The validation error "Got error: 401 Client Error: Unauthorized for url" will appear because the activiti client only from the saved to db confi: https://github.com/maykinmedia/django-activiti/blob/a93c90498e8609834736f6fd4d545ade577c2aa4/django_activiti/models.py#L56

**Comment by sergei-maertens** [comment]
Fixed in 4c5b8daaba9dae0b6dd00cb0ca821f521b6e31d1
